
STR = hello
STR2 = hello
STR2 += world! # += 追加赋值

test1 = a
test1 ?= b # ?= 是条件复制，如果test1没有被复制，则赋值b。否则，无事发生
test2 ?= b

all:
	@echo "STR = $(STR)"
	@echo "STR2 = $(STR2)"
	@echo "test1 = $(test1)"
	@echo "test2 = $(test2)"
